/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClearStorage: typeof import('./src/components/ClearStorage.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    RandomCode: typeof import('./src/components/RandomCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TurnTable: typeof import('./src/components/TurnTable.vue')['default']
    VanField: typeof import('vant/es')['Field']
    VanOverlay: typeof import('vant/es')['Overlay']
  }
}
